### ISSUE TITLE
TFRS - System throws an error when expanding rows in the Notifications page

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2812]
**Describe the Bug**
System throws an error when expanding rows in the Notifications page. Error only appears to happen when expanding from the default of 10 rows to 25, 50 or 100. Expanding to 15 or 20 rows does not throw an error. 

Error appears to only be impacting IDIR users; however, BCeID user test accounts don't have many notifications to load as the error may be caused by trying to load a large amount of data (notification entries). 

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: IDIR user
1. Go to Notificaitons page by clicking on the Bell icon in the top nav bar
2. Click on "10 rows" selection at the bottom of the react table
3. Select 100 rows

**Screenshot of error:**
![Image](https://github.com/bcgov/tfrs/assets/47334977/3077f934-74db-4daf-9a92-86b87b73aeb7)

![Image](https://github.com/bcgov/tfrs/assets/47334977/d5266727-df6d-45af-a25d-33e18c25eb0a)

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/tfrs/2812?planning-poker) with Zenhub @hamed-valiollahi @kevin-hashimoto @prv-proton

**Comment by AlexZorkin** [comment]
Minio Error associated with Notifications api call.

[Previous line repeated 2 more times]
File "/opt/app-root/lib64/python3.9/site-packages/urllib3/connectionpool.py", line 884, in urlopen
retries = retries.increment(method, url, response=response, _pool=self)
File "/opt/app-root/lib64/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='tfrs-minio-test.apps.silver.devops.gov.bc.ca', port=443): Max retries exceeded with url: /tfrs?location= (Caused by ResponseError('too many 503 error responses'))
