### ISSUE TITLE
TFRS - Available Credit Balance date restriction bug

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2867]
**Describe the Bug**
This bug is affecting a feature that is meant to prevent compliance units acquired in future periods from being used to achieve compliance with previous periods.

This bug is occurring in the TFRS dev environment. As an IDIR user, I am able to create a historical data entry (HDE) credit transfer and Initiative Agreement (IA) with a recorded date after March 31st, 2024 and then as a BCeID user, apply these compliance units to compliance reports from previous years. 

![Image](https://github.com/bcgov/tfrs/assets/156380046/1c70ab5c-b32d-4362-b324-72ca0b4f1dcc)

As a BCeID user in the TFRS dev environment, I can complete a compliance unit transfer with another organization that is recorded by the director with a date after March 31st, 2024 and I am still able to use these compliance units in a compliance report from previous years (2019-2023). 

Transfer 1:
![Image](https://github.com/bcgov/tfrs/assets/156380046/a45656b2-e00c-4150-bd98-c643c7cc0978)

Transfer 2:

![Image](https://github.com/bcgov/tfrs/assets/156380046/24578cf7-11b2-4046-9813-6039b8b14067)

Note: This bug appears to not be impacting Prod, but it is difficult for us to confirm given that it is a BCeID-side issue. Discussions with two organizations that are trying to submit their 2023 compliance reports have lead us to believe that this bug is not occurring in Prod. However, it is difficult for us to confirm with certainty. The two organization IDs are #509 (report #2930) and #609; we cannot provide the specific report ID for organization #609 because we cannot see their draft as IDIR users, however they are attempting to submit for their 2023 compliance report. Organization ID #609 has not yet submitted a 2023 compliance report; organization #509 has submitted a 2023 compliance report and is now trying to submit a supplemental 2023 compliance report. The developer that works on this card may want (should) consider pulling the TFRS prod data as part of the testing procedure to fix this bug. 

**Expected Behaviour**
If an IDIR user uses the HDE feature to complete a transfer of compliance units with a date after the March 31st reporting deadline, this amount of compliance units should not be part of the organization's available credit balance for reporting in previous compliance periods. The BCeID user should not see these credits available for use in their available credit balance to apply to compliance reports from previous years. 

**Actual Behaviour**

The following highlighted transactions (1 Initiative agreement ID #1405 and two compliance unit transfers ID #1406 and #1409) of 100 units each have a recorded date that falls after March 31st, 2024.

![Image](https://github.com/bcgov/tfrs/assets/156380046/038b8685-b74d-46cb-9848-1763c17e5e75)

The organization's compliance balance is 1706 total (1,000 was a rescinded transfer, 406 was their 2019 report assessment and 300 are the 3 transactions noted above with a recorded date after March 31st, 2024). The actual behaviour of the TFRS dev environment shows the same available balance for each year, even though transfers with a recorded date past March 31st, 2024 should not be included in an available balance for any previous years (2019-2023 reporting):

2020 compliance report draft available balance:

![Image](https://github.com/bcgov/tfrs/assets/156380046/b271bd41-51c4-453f-94d6-c48737227668)

2021 compliance report draft available balance:

![Image](https://github.com/bcgov/tfrs/assets/156380046/28ee5646-c579-49ab-af57-c19e1c76b745)

2022 compliance report draft available balance:

![Image](https://github.com/bcgov/tfrs/assets/156380046/ba7fb0d5-8df4-43c0-8902-b27346af716b)

2023 compliance report draft available balance:

![Image](https://github.com/bcgov/tfrs/assets/156380046/357c5519-65e4-452e-b999-712db799e149)

I was able to apply all these compliance units to a 2023 compliance report and select 'submit', even though 300 of the compliance units should have been unavailable for use. Please see screenshot:

![Image](https://github.com/bcgov/tfrs/assets/156380046/89aac883-e640-442b-9c02-3bf7e278b113)

**Implications**
The implications for this bug in the dev environment means that there are no restrictions in place to prevent a BCeID user from using compliance units acquired in future periods to achieve compliance with previous periods. This means that a BCeID user could avoid a penalty situation by purchasing compliance units in later years to apply to previous compliance units. 

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: BCeID user
1. Go to transactions
2. Complete all the steps of a new transfer, up to recording the transfer as an IDIR user with the director role
3. Return to receiving organization's BCeID account and start a compliance report for a previous year (2019-2023)
4. See new compliance units added to 'available compliance unit balance' in the compliance report. 
5. Go to 'Summary and declaration' tab and see ability to use these newly acquired compliance units and submit your report.
  
Additional information:
Lindsy has a theory that this may be related to supplemental reporting, either as a true supplemental report or as a new compliance report after a first edition of a compliance report draft has been deleted. Testing accounts have a very limited availability of brand new compliance reports to test, so it is unclear if this bug is occurring with compliance reports that are brand new to the system for the first time. 

Visual representation of available compliance unit balance for reference:
https://bcgov.sharepoint.com/teams/08333/Shared%20Documents/General/Business%20concepts%20and%20process%20workflows/Available%20Compliance%20Unit%20Balance%202023-07-26.jpg?csf=1&web=1&e=IICkvy&isSPOFile=1&OR=Teams-HL&CT=1712161376085&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiI0OS8yNDAyMjkyNDUxNyIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D&cid=a0b77e4a-a36f-4db0-adba-809ff683b7ee

**Comment by Grulin** [comment]
Tested again with different organizations in TFRS dev and could not recreate the bug. Seems to be specific to FS6 organization in the dev environment.

**Comment by Grulin** [comment]
Tested again with TFRS dev organization FS2 and the bug is still there.

**Comment by Grulin** [comment]
The fix is working for restricting transfers reflected in the available balance on compliance reports to the compliance period and future periods only (tested a 2024 transfer, a 2022 HDE transfer and IA). Transfers done in 2024 are not reflecting in the available balance for previous periods (2019-2023) and HDEs done are showing in the available balance for the correct effective date and future periods, but not previous periods (as it should). 

The only scenario I seem to be having trouble with is accepting a 2019 supplemental report that would change the organization's positive balance (4,608) to a negative balance that added 8,789 debits (total would be -4181). As an IDIR user with the director role, I get the following error when I try to 'Accept' this report:


![Image](https://github.com/bcgov/tfrs/assets/156380046/03490e80-eb03-4fd3-8356-acad9099eb81)

I'm guessing that this is because it would invalidate all the organization's transfers after that (like if in 2021 they sold some of their 4,608 credits or they had applied 1,000 of these credits earned to their 2020 report that has been processed). I'm not sure what we want to do about this. Do we restrict supplemental reporting that would take an organization from a credit position to a debit position for previous years?

**Comment by Grulin** [comment]
@AlexZorkin I've done some testing on this the past two days. I've noted the following:

The supplemental report is using the previously reported credits earned to offset the penalty by -4,608. In this scenario, the supplier's original report would have earned 4,608 credits, but the supplemental shows they replaced that reported volume with the generation of -8,789, meaning the previously earned credits didn't actually exist as they actually generated way more debits than they first reported. With the supplemental report correction, the previous credits earned from reporting should be neutralized and the supplier should be in a penalty situation for the entire debits earned from this new report (-8,789). Currently, TFRS is recognizing the 4,608 credits from the original report and applying it to the debits (-8,789) for a total debit scenario of -4,181 and calculating the penalty based on that (4,181 x $200 = $836,200 penalty).

I think the error is that the supplemental math is calculating the total credit/debits as in addition to the previous report, when in fact, the new report should be replacing the old report in this scenario. I don't know if this is the case for all reports as we have other scenarios where a supplier adds volume and it can be in addition to previously reported volume, but this scenario is almost like a full replacement of the original report. 

I'd say it's safer for us to treat supplemental reports as completely new replacement reports rather than additions for these kinds of scenarios, but I don't know what the implications are for that. 

Please let me know if you want me to go through this with you. It's a lot of info and I hope I made sense.
